#!/bin/sh
python createdb.py
python mnlp/manage.py syncdb --noinput
python mnlp/manage.py migrate --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static/heatmaps
python mnlp/manage.py collectstatic --noinput
crontab ~/current/jobs/crontab